### ISSUE TITLE
Should Constance be usable even in sessionless / adminless project ?

### ISSUE THREAD

**Issue by ldng** [jazzband/django-constance#181]
More than a problem it is an interrogation.
Is it possible to use constance 'headless', that is without the admin.

We would like our production app to be sessionless and thought we could use constance
with the DB backend and edit settings with the model.
```python
>>> from constance.backends.database.models import Constance
>>> service_conf = Constance.objects.get(key='WEBSERVICE')
>>> service_conf.value = 'http://...'
>>> service_conf.save()
```

But than in the shell (and the running project), it returns the default value from the config file :
```python
>>> from constance import config
>>> config.WEBSERVICE
'127.0.0.1:5050'
```

I get that the admin interface is dependant on session but I would have expected the core
not to depend on it.

### System configuration

* Django version: 1.10.3
* Python version: 3.5.2

```python
INSTALLED_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'constance',
    'constance.backends.database',
    ...
)

MIDDLEWARE = [
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
]
```

**Comment by jezdez** [comment]
@ldng Sure you should be able to use constance without the admin. Simply use the `constance.config` object to set the value. Don't write to the database directly via the model since there is caching involved and setting values directly will prevent the cache invalidation to work correctly. This is by design since the backends are implementation details and differ in the way they work behind the scenes (Django ORM vs. Redis commands).

So this should work for you:

```python
from constance import config
config.WEBSERVICE = 'http://...'
```
