### ISSUE TITLE
Reset to default not working on datetime widget

### ISSUE THREAD

**Issue by camilonova** [jazzband/django-constance#185]
### Describe the problem

The reset to default link is not working when having a datetime widget.

![screen shot 2016-12-23 at 5 59 26 pm](https://cloud.githubusercontent.com/assets/202559/21463617/c535e26e-c939-11e6-9122-ac50c77518c4.png)

I guess you have to split the value and convert it, since the value shown is different than the one used at the input.

### Steps to reproduce

Add a datetime as a constance value

### System configuration

* Django version: 1.10
* Python version: 3.5

**Comment by camilonova** [comment]
@rvernica Can you please take a look?

**Comment by rvernica** [comment]
OK, will do.

**Comment by camilonova** [comment]
Maybe the best think would be to disable the reset feature if we have more than one input widget.

**Comment by rvernica** [comment]
For `DateTime` type, instead of one field (`ID`) that we have to populate, there are two fields, one with `ID_0` and one with `ID_1`. Populating them should not be hard... The problem is getting the default. The default that is available in HTML is already localized and may be hard to split.

The current code does not even work for `Date` or `Time` types because the default available in HTML is localized:
![date-constance](https://cloud.githubusercontent.com/assets/241185/21486708/cea70400-cb6d-11e6-8b5b-c5f7ea9ac354.png)

A solution that would help with all three types would be to provide a raw default to the HTML view. For `DateTime` this default could be a tuple of two values, one for each part. Fixing the HTML and JavaScirpt should be easy once appropriate values as available.

**Comment by jezdez** [comment]
Hm, I wonder if we should revert the reset to default feature, it kind of has evolved in all kinds of UI problems, which hurts constance reputation as a simple and stable tool. Anyone care to weigh in on this?

**Comment by rvernica** [comment]
I might be biased but I think the feature is useful. I see its usefulness in one of the projects where I use constance. I think the issues can be addressed.

**Comment by jezdez** [comment]
@rvernica Oh it's definitely useful, don't get me wrong, just I wondered if we need more time fleshing out the feature before re-adding it again? I'm also happy if you think we can figure out the various edge cases.

**Comment by rvernica** [comment]
See PR #192 for a fix to this issue.

**Comment by SebCorbin** [comment]
This seems to be solved, can't reproduce with last version
