### ISSUE TITLE
Migration error for multiple databases: django.db.utils.ProgrammingError: (1146, "Table 'db_2.django_content_type' doesn't exist")

### ISSUE THREAD

**Issue by sholleman** [jazzband/django-constance#210]
### Describe the problem

Hi. We have a django site that uses 4 databases. I'm trying to install Constance on our Django site and am getting an error regarding the django_content_type table in one of the non-default databases. 

We've written a DB router to route selected apps to specific databases. Non-specified apps route to default. Because Django, we have a script to run the migrations for all the databases. 

```
python manage.py migrate --noinput 
python manage.py migrate --noinput --database=db_2 
python manage.py migrate --noinput --database=db_3 
python manage.py migrate --noinput --database=db_4 
```

Running the script gives the following error when it runs the db_2 command:

```  
Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying database.0001_initial... OK
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/sholleman/src/.virtualenvs/sma/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line

[...]

Migration error: django.db.utils.ProgrammingError: (1146, "Table 'db_2_staging.django_content_type' doesn't exist")
```

We considered creating a  `django_content_type` tables each database, but that feels wrong. Removing the two instances of `.using(using)` from create_perm() in apps.py stops the error, but breaks one of your tests, `test_post_migrate_signal_creates_content_type_and_permission_in_secondary_database`. I think the error is due to a disconnect between the migration and the post-migrate signal. The migration looks to our custom db router and doesn't do anything to db_2. But the create_perm() in apps.py is ignoring our db router. Do you have any suggestions for fixing this? 

### Steps to reproduce

- Have a multi-database site with a special DB mapping router to route model calls to the correct database. Only the default database has the table, `django_content_type`.
- Install Constance with database backend. 
- Run migrations for non-default database. e.g., `python manage.py migrate --noinput --database=ib_files`
- Error

### System configuration

* Django version: 1.8.15
* Python version: 2.7.12

**Comment by jezdez** [comment]
First, I'm sorry you have 4 databases. I hope you understand that a out-of-the-box tool like constance doesn't often target this type of system when it's developed.

I would argue we could fix this by making sure we pick up the correct router in the code that creates the permissions. Since I'm not sure how custom your routers are, I'd suggest to implement a signal handler override that hard codes your router into the call of `create_perm` and see what the passed `using` parameter contains. Then decide to either just override the whole constance app config to abide by your router or find a different way. Using the `using()` queryset method is definitely the official way to go about it, so I'm concerned this showed up for you at all. Either way, please report back.

**Comment by camilonova** [comment]
Fixed in #258

**Comment by sholleman** [comment]
@camilonova Awesome. Thank you!

**Comment by Jorgecardenas1** [comment]
0

I have to face same issue and there are a couple of approaches, but the one I think is the most probable one.

Maybe you are loading views or queries to database but you haven´t granted enough time for Django to migrate the models to DB. That's why the "table doesn't exist".

Make sure you use this sort of initialization in you view's code:

Class RegisterForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

A second approach is you clean previous migrations, delete the database and start over the migration process.
