### ISSUE TITLE
question : override_config on testcase - setup

### ISSUE THREAD

**Issue by liormaynhypr** [jazzband/django-constance#214]
Hey,
I started using constance today and I wanted to use the override_config decorator on my tests.
to make sure it works i printed the values in the class method setUpTestData - and than i discovered that they are not changed.

in the test itself the values are corresponding to the values i put in the override_config, but the setup class method doesn't seem to know the new values.

was that done on purpose? or is it a bug?

also -another question - is it possible to change the settings values from python? and not via admin? couldn't find anything about that in the docs.

thanks in advance:)

* Django version: 1.9.1
* Python version: 2.7.10

**Comment by jezdez** [comment]
IIRC  the `setUpTestData` method isn't currently part of the scope of the decorator but only the test methods themselves. I'm not sure if this is easily changed, or at least I personally don't know how to do it better. But there is a chance that taking another look at the current Django code for the `override_settings` deccorator that the `override_config` decorator was based on could help fix this. So to answer your questions: not on purpose, probably a bug, definitely a missing feature. Help would be appreciated.

To answer your other question, right now constance supports two APIs: the constance management command and admin integration. Since there is data validation involved when setting config values via those APIs, offering a sensible code level API was never actively worked under fear of opening the config value setting to malicious data injection. The [*private* API here](https://github.com/jazzband/django-constance/blob/master/constance/management/commands/constance.py#L13-L26) (read: unsupported and not guaranteed to work for your case) shows what's involved.
