### ISSUE TITLE
Importing/Exporting config to a JSON or YAML file

### ISSUE THREAD

**Issue by thongly** [jazzband/django-constance#247]
CC: @jezdez as per our discussion on the other thread.

### Describe the problem

I would like to know whether there's a suggested method to import/export current, actual configs (i.e. the configs that are actually being used on a production system) to a file, such as a JSON or YAML file, which can be reloaded if necessary.

### Steps to reproduce

N/A

### System configuration

* Django version: 1.11
* Python version: 3.6

**Comment by jezdez** [comment]
Right now there isn't a way to do that, but I could see this being added as `import`/`export` subcommands to the [constance management command](https://github.com/jazzband/django-constance/blob/29f493f7c1e0221129145f609b22d970db3e8a9a/constance/management/commands/constance.py).

YAML isn't a good idea since there isn't a yaml encoder in the stdlib and I wouldn't have to rely on one just to get the feature. Lets just use json and emit the result to stdout. E.g. running this would make sense to me:

```
./manage.py constance export
```
```json
{
  "MY_CONFIG": "lalalala",
  "CACHE_TIMEOUT": 60,
  "MAINTENANCE_MODE": true
}
```

Or just `n` values `./manage.py export MY_CONFIG CACHE_TIMEOUT`:
```
{
  "MY_CONFIG": "lalalala",
  "CACHE_TIMEOUT": 60
}
```

Importing also either via stdin or an optional file:
- `echo config-2017-11-27.json | ./manage.py import`
- `./manage.py import -f config-2017-11-27.json`

Or just  `n` values:
- `./manage.py import -f config-2017-11-27.json MY_CONFIG`


Taking data via stdin would allow centralized storage of config values on an internal config server for example, or easy set for Open Source packages.

**Comment by jezdez** [comment]
Actually let's use `dump`/`load` instead of `export`/`import` since the latter are so tied to the module system.

**Comment by havocbane** [comment]
Can I ask why this was closed? I tried using `dumpdata` with `constance` as the app label, but it just returns an empty result:

`$ python manage.py dumpdata constance
[]`

Is there a known way to export/import constance data?

**Comment by camilonova** [comment]
You can use the `list` command:

`$ python manage.py constance list`

**Comment by raphodn** [comment]
Same here, it would be great to have working `dumpdata` and `loaddata` commands.
I was looking for a way to load/view/edit config and variables, and I'll probably go for a simple model (with just 1 record) instead

**Comment by alexkiro** [comment]
A solution for this is to use dumpdata/loaddata fixtures. **NOTE** this only works if you are using the _Database_ backend:

```
python manage.py dumpdata database.Constance --indent=2 -o constance.json
```

Then to import 

```
python manage.py loaddata constance.json
```
