### ISSUE TITLE
Ordered Fields

### ISSUE THREAD

**Issue by Mogost** [jazzband/django-constance#364]
**django-constance** does not store ordering of `CONFIG_FIELDSETS` without using OrderedDict

As of Python 3.6, for the CPython implementation of Python, dictionaries remember the order of items inserted. For 3.7+ that is rule. https://stackoverflow.com/a/39980744/5628843
That is happening due to [code](https://github.com/jazzband/django-constance/blob/master/constance/admin.py#L273):
```python
            if not isinstance(settings.CONFIG_FIELDSETS, OrderedDict):
                context['fieldsets'].sort(key=itemgetter('title'))

        if not isinstance(settings.CONFIG, OrderedDict):
            context['config_values'].sort(key=itemgetter('name'))
```

This code was written at a time when dictionaries had no guarantee of order.
In my opinion, this code should be brought up to date.

I see the following points:
1) For people who use OrderedDict, everything should work without any changes.
2) People whose python does not guarantee the insertion order should continue to receive the sorted version.
3) I'm not sure, but maybe we should save the opportunity for people using modern python to get a sorted version. There must be an option for this. Although in fact we can do without it.

My motivation is that a regular dict looks a lot simpler than an OrderedDict

* Django version: 2.2
* Python version: 3.6

cc: @jezdez @camilonova

**Comment by camilonova** [comment]
Sounds good to me. PRs are welcome!

**Comment by Mogost** [comment]
I think that issue must be open for now

**Comment by camilonova** [comment]
I think otherwise, since you can open a PR anytime you have a concrete work to review there is no point on keeping an issue open.

**Comment by jezdez** [comment]
Hey @camilonova, just a quick heads-up, I do think it's perfectly reasonable to have an issue open if and when it helps develop a solution for a version compatibility issue such as this.

Please remember that the moniker "PRs are welcome" can be easily misunderstood as dismissive and not as welcome as intended. While PRs are often welcome, unclear issues are sometimes hard to triage, and I believe this issue is a good example for not having a clear path forward.

@Mogost I'd suggest to clarify what you think is best to move ahead with this issue, and providing example code in a PR is a reasonable ask.
