### ISSUE TITLE
How do I set settings keys for other libraries I’m using in my project?

### ISSUE THREAD

**Issue by ericswpark** [jazzband/django-constance#481]
### Describe the problem

I’m trying to add django-constance to my project. One of my dependencies has a configuration key that I’d like to configure within Constance. Unfortunately, I cannot import Constance within `config/settings.py` as it will cause all the tests to fail (and also I’m not sure if this is allowed — if my understanding is correct `settings.py` sets up all the Django apps and what not and calling Constance before Django has set up all apps could cause undefined behavior?)

So given a standard Django configuration key defined in `config/settings.py`, how do I set that key using Constance?

**Comment by ericswpark** [comment]
Right, but the problem is the app is a library that I cannot modify, that calls configuration values from `django.conf`.

I *could* technically fork the library and make the changes, but this becomes infeasible over time as I add more dependencies, increasing the number of config values I need to adjust.

**Comment by NoPH8** [comment]
In that case you can take a look on [signals section in the constance docs.](https://django-constance.readthedocs.io/en/latest/#signals)
But I think it's not a good idea because of [django warns about altering settings in runtime](https://docs.djangoproject.com/en/4.0/topics/settings/#altering-settings-at-runtime). And this can cause various errors especially when runs multiple instance of django app.

**Comment by ericswpark** [comment]
Thanks @NoPH8. After reading some more posts and the documentation it seems like there is currently no way to achieve this without modifying said library or just forcing the user to set up the settings before starting the server.
